{% set name = "aiologic" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiologic-{{ version }}.tar.gz
  sha256: 2aa851d2298588f9bfa543a425773e8c3e07069f96c09ccc7106c0dd899fe5fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - wrapt >=1.16.0

test:
  imports:
    - aiologic
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/x42005e1f/aiologic
  summary: GIL-powered* locking library for Python
  license: ISC
  license_file: ISC.txt
  dev_url: https://github.com/x42005e1f/aiologic
  doc_url: https://aiologic.readthedocs.io/latest/

extra:
  recipe-maintainers:
    - xylar
